package com.edhollingsworth.geotrak.trakker.model;

import java.time.OffsetDateTime;

import io.quarkus.runtime.annotations.RegisterForReflection;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

/**
 * GeoTrak event model.  Represents a geographic position, logged by a
 * specific GeoEntity, at a specific date and time.
 * 
 * @author Ed Hollingsworth
 */
@Data
@Getter
@Setter
@RegisterForReflection
public class GeoTrak {
	//@Query(name = "id", description = "Autogenerated ID of the GeoTrak event")
	private String trakId;
	//@Query(name = "geoId", description = "Unique ID of the GeoEntity")
	private String geoId;
	//@Query(name = "lat", description = "Latitude")
	private float latitude;
	//@Query(name = "long", description = "Longitude")
	private float longitude;
	//@Query(name = "alt", description = "Altitude (in meters)")
	private float altitude;
	//@Query(name = "timestamp", description = "Timestamp of this GeoTrak event")
	private OffsetDateTime timestamp;
}
